# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

volumes:
  datafiles:

services:
  db:
    image: mysql:latest
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=global@accelerex
      - MYSQL_USER=global@accelerex
      - MYSQL_PASSWORD=global@accelerex
  api:
    build:
      context: .
      dockerfile: DockerFile
    depends_on: 
      - db
    ports:
      - "8888:80"
    restart: always
    environment: 
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
